### ISSUE TITLE
Code Example Error

### ISSUE THREAD

**Issue by BrokenShoeLace** [dotnet/dotnet-api-docs#10026]
For many years, it used to be the following in C#:

`System.Diagnostics.Process.Start("https://microsoft.com");`

but this no longer works in Windows Forms with Net Core 8, as it gives the error (see below) about a Working Directory. In order to do the same, you now need to do:

`using System.Diagnostics;

Process.Start(new ProcessStartInfo { FileName = "https://microsoft.com", UseShellExecute = true });`

The error in detail:

**System.ComponentModel.Win32Exception**: 'An error occurred trying to start process 'https://microsoft.com' with working directory 'F:\Users\[REDACTED]\source\repos\PATH_TO_PROJECT\bin\Debug\'. The system cannot find the file specified.'

Hope this help

**Comment by adamsitnik** [comment]
Hi @BrokenShoeLace 

This is by design, as we have changed the default value of `UseShellExecute`:

https://learn.microsoft.com/en-us/dotnet/core/compatibility/fx-core#change-in-default-value-of-useshellexecute

I can see that this is already mentioned in the docs:

https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=net-8.0#property-value

> The default is true on .NET Framework apps and false on .NET Core apps.

I agree that it's still not perfect (you need to get the error, search on the web and find the information about the change), but I am not sure how we could improve the user experience. Please let me know if you have any ideas.
