### ISSUE TITLE
fix value of Math.PI in syntax section

### ISSUE THREAD

**Issue by ericbl** [dotnet/dotnet-api-docs#1094]
Please fix the first chapter on this page with the same value as in the remarks and source code:
https://referencesource.microsoft.com/#mscorlib/system/math.cs,fa5fd1f4e5f6f911

On the other hand, the value in remarks and source have 20 digits, which is higher than the significant digits of a double (17), explaining why reflection does NOT show the same value. It does not make much sense. 
Having PI as decimal internally would increase its accuracy, but I suppose it will apply a big change in the whole Math library. Even dedicated external library such as Math.NET is using double for PI constant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8047bcfa-00dd-5106-d44d-9d8ac49e664f
* Version Independent ID: a73a472c-a3be-e54e-0354-7d3a224be282
* Content: [Math.PI Field (System)](https://docs.microsoft.com/en-us/dotnet/api/system.math.pi?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Math.PI);k(DevLang-csharp)%26rd%3Dtrue&view=netframework-4.7.2)
* Content Source: [xml/System/Math.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/Math.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by ziron999** [comment]
This can just be a float? why not just make it that?

**Comment by rpetrusha** [comment]
A float would be a poor choice, @ziron999, because a float is significantly less precise that a double. Math.Pi is most commonly used with Doubles, which requires a widening conversion of a less precise Single to a Double.

Thanks for raising this issue, @ericbl. The syntax section is auto-generated by reflection; I've opened an issue mono/api-doc-tools#412 to address this issue, which I suspect is caused by retrieving the value using the default ("G") format specifier with default precision.

Over the short term, we can fix this by opening a PR to modify the value in the syntax section, which I'll do shortly. This is a stopgap fix, though, since that change will be overwritten the next time that the reflection process updates the API reference. This will be the case until mono/api-doc-tools#412 is addressed.

You also raise an interesting question about the 20-digit assignment being greater than the 17-digit precision of a Double. This is the definition of Math.PI from assembly metadata (and the value produced by the "G17" format string):

![image](https://user-images.githubusercontent.com/10886961/52369326-51f93380-2a05-11e9-9833-b046fcda7cf9.png)
 
My sense is that that's a better value to use (especially since, if mono/api-doc-tools#412  is addressed, that would be the value retrieved using reflection. Thoughts, @tarekgh, @tannergooding?

**Comment by tannergooding** [comment]
> which is higher than the significant digits of a double (17)

This is not quite accurate. A double-precision value has 1 sign bit, 11 exponent bits, and 53 mantissa bits (one of which is implicit). This ultimately means that you need no more than 17 significant digits to guarantee that a given string can roundtrip back to the original value. The exact value represented by the double may actually contain more digits and in some cases you may need less than 17 digits for the string to roundtrip correctly. For example, the exact representation of `double.Epsilon` (which is the longest exact string) contains 1075 digits, 768 of which are considered "significant" (the remaining 307 are leading zeros), however the shortest roundtrippable string is actually `5E-324`.

> This can just be a float? why not just make it that?

We also have `MathF.PI` which exposes the value as a float constant.

> Thoughts, @tarekgh, @tannergooding?

@rpetrusha, We should likely be using `G17` for any double values and `G9` for any single values that are printed in documentation. This is the safest option since, otherwise, full framework and versions of .net core prior to 3.0 will not always produce a string that roundtrips to the original value (even when using `R`).
In .NET Core 3.0 and on; we could just use `ToString()`, `ToString("G")`, or `ToString("R")` as all three will now provide the shortest roundtrippable string.
However, I imagine no matter what we decide to do there will be some level of confusion. People will question why the value is off from actual `PI`, they will ask why it only displays 17 significant digits, they will ask why the result differs from their own `ToString()` call, etc.

**Comment by tannergooding** [comment]
We could probably also update the source-code to just use the shortest roundtrippable string (which in this case is 17 digits). The same could be done for `Math.E`, `MathF.PI`, and `MathF.E` (the latter two which have 9 digits in the shortest roundtrippable string)

**Comment by rpetrusha** [comment]
That sounds good. I can take care of opening all the PRs.

**Comment by ziron999** [comment]
> 
> 
> A float would be a poor choice, @ziron999, because a float is significantly less precise that a double. Math.Pi is most commonly used with Doubles, which requires a widening conversion of a less precise Single to a Double. For PI as a float, though, you can use [MathF.PI](https://docs.microsoft.com/dotnet/api/system.mathf.pi?view=netcore-2.2).

on the contrary it's things like this that will make every version of the .net framework never be as good as the original...
right there you are limiting possibilities due to problems that can not be accounted for.
