### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by WillSullivan** [dotnet/dotnet-api-docs#1287]
Look, EF docs at this level are almost nonexistent. And here you are, tempting me with a link to a "Metadata Workspace Overview." I practically broke my finger clicking that link, and it leads to 

``` text
We're no longer updating this content regularly. Check the Microsoft Product Lifecycle for information about how this product, service, technology, or API is supported.
```

Why do you hate me? What did I do to you? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 50fce505-544f-66d2-5322-1f9b7901c775
* Version Independent ID: 7125aaf3-74fa-f1d2-1489-f555648cc5a8
* Content: [DataSpace Enum (System.Data.Metadata.Edm)](https://docs.microsoft.com/en-us/dotnet/api/system.data.metadata.edm.dataspace?view=netframework-4.7.2)
* Content Source: [xml/System.Data.Metadata.Edm/DataSpace.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data.Metadata.Edm/DataSpace.xml)
* Product: **dotnet-api**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by mairaw** [comment]
Thanks for your feedback @WillSullivan. We're facing some redirections issues as we retire the MSDN content. 

I'll update that link to go to https://docs.microsoft.com/en-us/previous-versions/bb399600(v=vs.90) for now.

@divega do you have any suggestions on a better link inside the EF docs?

**Comment by divega** [comment]
@mairaw I don't have a better suggestion. 

Things are complicated because several versions of EF exist. 

That particular page about MetadataWorkspace seems to be from a very old EF documentation set and not part of the set we ported to https://docs.microsoft.com/ef/ef6. 

In fact, the source of the link is the API reference docs from the legacy version of EF that ships in .NET Framework (aka EF4). 

The EF6 API reference at https://docs.microsoft.com/dotnet/api/system.data.entity.core.metadata.edm.dataspace?view=entity-framework-6.2.0 doesn't have the link. 

Any time I run into one of those loose pages, I add to a list I am tracking at https://github.com/aspnet/EntityFramework.Docs/issues/668. It may make sense to consolidate at least some of those into the EF6 docs. 

Let me know if you have any thoughts.

**Comment by divega** [comment]
> If you think there's anything we should do to push customers to newer versions, like a note in the remarks or something, then we can plan this for a future sprint.

I think it make sense to point customers doing active development on EF4 to at least upgrade to EF6. That gives them great compatibility, lots of improvements, and a path to .NET Core 3.0. So if something like this can be done, that would be great.

**Comment by WillSullivan** [comment]
Sorry, there was no indication of the version it was covering (am 6.x, thought the docs were recent enough). Am here because I'm in the process of rewriting the query tree via an interceptor and omg the lack of docs on the subject... The ultimate goal is more complex row level filtering (aka where tenantId = derp is for wimps). Not much docs on the subject. Interception whether it is in Core or in 6.x is, if they are designed similarly, the goal is rewriting the query tree.

**Comment by divega** [comment]
@WillSullivan in case you haven't found it, @rowanmiller has an example of a soft delete query interceptor at https://github.com/rowanmiller/Demo-TechEd2014/tree/master/FakeEstate.ListingManager/Models/EFHelpers. 

The command trees from EF are indeed a complex area that never git a lot of documentation, mainly because it was designed only to be used in extremely advanced scenarios and we didn't see much demand. However a good understanding of LINQ expression trees should give you a good head start. 

EF Core doesn't have an interception features like EF6, but you can use service replacement and intercept diagnostic events to accomplish similar tasks. Instead of having its own expression trees, EF Core uses LINQ expressions and Relinq query models.

**Comment by WillSullivan** [comment]
I've pretty much looked everywhere and have seen everything online that's available. I'm old hat with Expressions, so I was able to pick up enough to get simple rewriting working. Now I'm stuck trying to figure out what the heck is up with TypeUsage and how to get from Type => DbExpressionBuilder.Parameter. 

I am in an extremely advanced scenario, trying to rewrite queries to include row level filtering (and I don't mean these simple scenarios that every single example or filtering framework supports). I'm not that far off; once I get my parameter I'm pretty much done.

**Comment by WillSullivan** [comment]
NVM that last bit, I figured out the beauty of binding in order to get variables.
