### ISSUE TITLE
IndexOf is missing

### ISSUE THREAD

**Issue by dbarnard-thorlabs** [dotnet/dotnet-api-docs#1429]
IReadOnlyList should logically include IndexOf.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dca4f85-6021-d495-c95b-8144585e8a3b
* Version Independent ID: 0e00932e-58d3-ba7d-f025-e0a7a9dd7151
* Content: [IReadOnlyList&lt;T&gt; Interface (System.Collections.Generic)](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlylist-1?view=netframework-4.7.2)
* Content Source: [xml/System.Collections.Generic/IReadOnlyList`1.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Collections.Generic/IReadOnlyList`1.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by mairaw** [comment]
Thanks for your feedback @dbarnard-thorlabs but this seems like a comment regarding the product and not the content. If so, I'd suggest you file an issue at https://github.com/dotnet/corefx to request API changes.
This issue seems related to your request: https://github.com/dotnet/corefx/issues/25459

And this is a related thread on SO: https://stackoverflow.com/questions/37431844/why-ireadonlycollection-has-elementat-but-not-indexof

But if I misunderstood your request, please let me know.

Also, your feedback made me check if there were any issues between what we had on MSDN and Docs and I discovered were not'showing inherited members on interfaces. So I'll file a new bug at https://github.com/microsoftdocs/feedback for our engineering team to investigate.
