### ISSUE TITLE
When to use ApplicationException then?

### ISSUE THREAD

**Issue by Devoney** [dotnet/dotnet-api-docs#1447]
We want to have a common base type for all application defined exceptions. We thought that ApplicationException could fulfill this purpose (I still think it can), but this page advises: `You should derive custom exceptions from the Exception class rather than the ApplicationException class.`. And at the same page it is stated ApplicationException `Serves as the base class for application-defined exceptions.`. In my opinion this counters itself. Also when deriving from Exception, there is no way to catch all application defined exceptions in one catch, we need a common base class for that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fafe04ef-184c-bbb9-01da-6926eae8dbb4
* Version Independent ID: db762610-dfd0-2e4c-4357-bd746317b128
* Content: [ApplicationException Class (System)](https://docs.microsoft.com/en-us/dotnet/api/system.applicationexception?view=netframework-4.7.2)
* Content Source: [xml/System/ApplicationException.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/ApplicationException.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by Zilounay** [comment]
From my understanding of this (and I asked myself the same questions as you did), it leads me to believe that `ApplicationException` is kind of obsolete.

Is this the case?

**Comment by rpetrusha** [comment]
Yes, it is the case. The guidance for using ApplicationException changed with the release of .NET Framework 2.0. An [old blog post from Brad Abrams](https://blogs.msdn.microsoft.com/brada/2004/03/25/introducing-the-net-framework-standard-library-annotated-reference-vol1/) explains why. Because it inherits from Exception but adds no new members, ApplicationException merely deepens the object hierarchy without providing any useful information.   

The documentation is clear in indicating that ApplicationException should neither be thrown nor caught. I'll close this issue.
