### ISSUE TITLE
Wrong documentation of default value of TextWriter.NewLine Property

### ISSUE THREAD

**Issue by MrM40** [dotnet/dotnet-api-docs#1477]
In .NET Core the default value seems to be equal to environment.newline, i.e. on Linux "\n", and not as stated in the documentation "\r\n". It might very well be true in .NET Framework, but not .NET Core.
The documentation state it also apply to .NET Core.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 311fad6a-3b2a-4f1e-fa8c-2945277f1d4a
* Version Independent ID: 54c411cd-5a3d-503b-541f-a70b4a7dcca7
* Content: [TextWriter.NewLine Property (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.textwriter.newline?view=netcore-2.2#System_IO_TextWriter_NewLine)
* Content Source: [xml/System.IO/TextWriter.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/TextWriter.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by frabe1579** [comment]
I agree, this can lead to bugs in some situations.
For me, I use TextWriter to send commands to a device via Telnet protocol. Everything is ok on Windows, but on Linux TextWriter sent '\n' and not '\r\n' as required by Telnet. I was sure the error was something else because documentation says that default is always '\r\n'.
Anyway, the xml comments of `TextWriter.NewLine` are ok, specifying that it is platform specific.
