### ISSUE TITLE
gethostbyname

### ISSUE THREAD

**Issue by RMeckstroth** [dotnet/dotnet-api-docs#1508]
"This API is now obsolete".  So what replaces it?  Duh!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64c87d2f-f78b-e69d-f6b2-2aac32a197cf
* Version Independent ID: 8cfc0f52-831d-a2c8-663f-c0e914a82ac0
* Content: [Dns.GetHostByName(String) Method (System.Net)](https://docs.microsoft.com/en-us/dotnet/api/system.net.dns.gethostbyname?view=netframework-4.7.2)
* Content Source: [xml/System.Net/Dns.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net/Dns.xml)
* Product: **dotnet-api**
* GitHub Login: @karelz
* Microsoft Alias: **ncldev**

**Comment by rpetrusha** [comment]
In this case, @RMeckstroth, the `Obsolete` attribute shown in the syntax section indicates the non-obsolete alternative API. It's [`Dns.GetHostEntry`](https://docs.microsoft.com/en-us/dotnet/api/system.net.dns.gethostentry).

Since the non-obsolete alternative is specified in the documentation, I'll close this issue.
