### ISSUE TITLE
How to use an xml schema from an .resx

### ISSUE THREAD

**Issue by LJ9999** [dotnet/dotnet-api-docs#1653]
Does anyone on this planet know how to read an xml schema from something OTHER than a file? Not all schemas are in files to be read. Yet every one of the 10,000 pages I've read here all assume the schema is in a file.

Some schemas are in databases. Some are in a static string. Mine is inline/embedded as a string resource.

Why is there no support for putting a schema stored this way in an XmlSchemaSet object?

Why is this so hard to do?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21ffa6e6-920f-498c-c707-47021be5093b
* Version Independent ID: 885cecae-da3c-faf4-c3fb-490650cdf4ca
* Content: [XmlTextReader Class (System.Xml)](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmltextreader?view=netframework-4.7.2)
* Content Source: [xml/System.Xml/XmlTextReader.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Xml/XmlTextReader.xml)
* Product: **dotnet-api**
* GitHub Login: @mairaw
* Microsoft Alias: **mairaw**

**Comment by REscobar** [comment]
The second line of the doucment recomends you to use a differente class `XmlReader`, but since you are reading from a .resx, I'm assuming you will have the string representing the xml already loaded in memory, and also I'm assuming you want an `XmlDocument` out of the string, if that is so here is the minimun required code:

```csharp
using System.Xml;

namespace ConsoleApp3
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            XmlDocument doc = new XmlDocument();
            doc.LoadXml(Resource1.MyXmlString);
        }
    }
}
```
![image](https://user-images.githubusercontent.com/348416/51801675-a979f100-2206-11e9-93bd-4d6fdc417259.png)

**Comment by mairaw** [comment]
Thanks @REscobar for your help. Does that help with your question @LJ9999?

**Comment by mairaw** [comment]
Closing due to the lack of response.
