### ISSUE TITLE
affect/effect issue

### ISSUE THREAD

**Issue by bamiata** [dotnet/dotnet-api-docs#1782]
The current text of this page reads:

The Text has no affect on the appearance of the NumericUpDown control; therefore, it is hidden in the designer and from IntelliSense.

Unless the text is very depressed, the "effect" should be used instead of "affect".
Also, the comma after therefore is superfluous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9b06a70a-b56c-2b8c-bc3e-a5c464beeb42
* Version Independent ID: 53c9eee9-9159-7593-4e67-6a9af85f4858
* Content: [NumericUpDown.Text Property (System.Windows.Forms)](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.numericupdown.text?view=netframework-4.7.2)
* Content Source: [xml/System.Windows.Forms/NumericUpDown.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/NumericUpDown.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
Thanks for your feedback @bamiata. Would you like to submit a fix for this?
Although I'd keep the comma after therefore since we usually add commas after introductory sentences such as this one.

Here are the instructions on how to make quick edits: https://docs.microsoft.com/en-us/contribute/#quick-edits-to-existing-documents

Here's the exact line number:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Windows.Forms/NumericUpDown.xml#L854

**Comment by bamiata** [comment]
Thanks... I just saw this and the affect/effect issue seems to be resolved, but perhaps during that resolution the h was dropped from has, which I've fixed.

**Comment by Potapy4** [comment]
@bamiata strange, but it looks as if someone has merged the old version of this file (with the word `affect`) - I fixed it
