### ISSUE TITLE
Use string.IsNullOrEmpty

### ISSUE THREAD

**Issue by NextTurn** [dotnet/dotnet-api-docs#1786]
`string.IsNullOrEmpty` is much faster than `== string.Empty`. While most of the time we assume that the string is not `null` when comparing it with `string.Empty`.

And `string.IsNullOrEmpty` provides better readability.

**Comment by mikedn** [comment]
That's kind of misleading:
* `string.IsNullOrEmpty` and `== string.Empty` are not equivalent
* the reason `IsNullOrEmpty` might be "much faster" has nothing to do with those hacks from the `IsNullOrEmpty` code, it has to do with the fact that `== string.Empty` involves actually comparing the 2 strings via `String.Equals`.

**Comment by NextTurn** [comment]
Thanks for your correction @mikedn. I've removed the code snippet.

**Comment by BillWagner** [comment]
This is an interesting discussion, especially in light of nullable reference types.  

The issue is the the empty string (or even a string with whitespace) are alternatives to null that represent the concept of a string with no data.

With respect to nullable references, we don't want people to remove `null` only to replace it with a different representation for "no data". In the instances changed in dotnet/samples#622 the empty string is from user input, so checking for null *and* the empty string is necessary. The key point here is that we should be careful how we change these checks to make sure we're not changing the semantics of the original code: Checking `IsNullOrEmpty` is semantically different than testing against `null`.
