### ISSUE TITLE
Archive bit

### ISSUE THREAD

**Issue by CeciAc** [dotnet/dotnet-api-docs#1992]
@Snegovikufa commented on [Tue Mar 05 2019](https://github.com/dotnet/dotnet-api-docs.ru-ru/issues/14)

According to https://en.wikipedia.org/wiki/Archive_bit seems that documentation for "Archive" field is wrong.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 7001712c-bcbb-d062-d857-cc94398fa32c
* Version Independent ID: bf49dcd7-ad7f-309a-53b0-c616a0f73951
* Content: [FileAttributes Enum (System.IO)](https://docs.microsoft.com/ru-ru/dotnet/api/system.io.fileattributes?view=netframework-4.7.2#feedback)
* Content Source: [xml/System.IO/FileAttributes.xml](https://github.com/dotnet/dotnet-api-docs.ru-ru/blob/live/xml/System.IO/FileAttributes.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by CeciAc** [comment]
Hi team,
I'm moving this here since the contributor is reporting an inconsistency
best

**Comment by MSDN-WhiteKnight** [comment]
Dotnet docs are are actually consisent with WinAPI docs on this constant:

[dotnet docs](https://docs.microsoft.com/en-us/dotnet/api/system.io.fileattributes?view=netframework-4.7.2#feedback)

>The file is a candidate for backup or removal.

[WinAPI docs](https://docs.microsoft.com/en-us/windows/desktop/fileio/file-attribute-constants)

>A file or directory that is an archive file or directory. Applications typically use this attribute to mark files for backup or removal .

Neither is contradicting Wikipedia, they just describe it differently. However, i do think that both can benefit from rewording, since current description is too brief in describing mechanics. Better wording should be something like that:

> This file is marked to be included in incremental backup operation. Windows sets this attribute whenever the file is modified, and backup software clears it when processing the file during incremental backup.

**Comment by rpetrusha** [comment]
Your proposed wording sounds good, @MSDN-WhiteKnight, except that perhaps "backup software should clear it" may be better, since it's not done automatically. Would you like to submit a PR to make the correction?
