### ISSUE TITLE
Websocket documentation

### ISSUE THREAD

**Issue by fredeil** [dotnet/dotnet-api-docs#2013]
**Issue description**

The websocket documentation is lacking for .NET Standard/.NET Core compared to .NET Framework.

See for example the difference between the _Remarks_ for `CloseAsync` and `CloseOutputAsync`:

__.NET Standard__
https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket.closeasync?view=netstandard-2.0

__.NET Framework__
https://docs.microsoft.com/en-us/dotnet/api/system.web.websockets.aspnetwebsocket.closeoutputasync?view=netframework-4.7.2

In the .NET Framework version you clearly get a view about the difference between `CloseAsync` and `CloseOutputAsync`. The same is true for many other methods.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [x] .NET Framework
- [x] .NET Standard

**Comment by mairaw** [comment]
Thanks for your feedback @fredeil. I've transferred the issue to our API docs repo.

The source of the documentation is the same across all targets. So are you saying that you like the remarks of the methods better on the AspNetWebSocket class vs. the WebSocket class?

Because the doc is exactly the same no matter which version you select:
https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket.closeasync?view=netstandard-2.0
https://docs.microsoft.com/en-us/dotnet/api/system.net.websockets.websocket.closeasync?view=netframework-4.7.2

Tagging @davidsh and @karelz here as well

**Comment by mairaw** [comment]
Closing due to the lack of information. We can reopen this if we understand your request a little better @fredeil.
