### ISSUE TITLE
Links shown in GetStartComSlot & GetEndComSlot documentation, point to documentation that can't be corrected

### ISSUE THREAD

**Issue by MarkFern** [dotnet/dotnet-api-docs#2295]
The [_"Introducing the Class Interface"_](https://msdn.microsoft.com/library/733c0dd2-12e5-46e6-8de1-39d5b25df024) link appears on the framework-4.7.2 documentation pages for the [_'Marshal.GetStartComSlot(Type)'_](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getstartcomslot?view=netframework-4.7.2) &  [_'Marshal.GetEndComSlot(Type)'_](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getendcomslot?view=netframework-4.7.2) methods.

The links appear at the end of the Remarks sections, each time as part of the following excerpt:
> _"...to pass slots within a specified range. For additional information, see [Introducing the Class Interface](https://msdn.microsoft.com/library/733c0dd2-12e5-46e6-8de1-39d5b25df024)."_

I've identified a possible mistake with the linked-to page. The possible mistake is described in issue [#11810](https://github.com/dotnet/docs/issues/11810) which even though refers to a different page, also applies to this linked-to page.

The problem is that the linked-to page cannot be updated or corrected (in the 'normal' way.) There's no button / link for leaving feedback or for suggesting edits to the page.

**Comment by rpetrusha** [comment]
Thanks for opening this issue, @MarkFern. The **Introducing the Class Interface** topic has been archived and is no longer being updated. Currently, there are no plans to migrate it into our active documentation set. 

However, we are currently in the process of revising the .NET interop documentation (see dotnet/docs#11396). Part of this work involves migrating selected archived content back into the active documentation set (see dotnet/docs#4649). I've added the topic to the list and reopened dotnet/docs#4649. And since this request can be tracked in there, I'll close this issue.
