### ISSUE TITLE
Possible doc error in DateTime.ToLongDateString()

### ISSUE THREAD

**Issue by jwatkin** [dotnet/dotnet-api-docs#2455]
The following page seems to incorrectly document the en-US pattern for ToLongDateString():
[https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tolongdatestring?view=netcore-2.2](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tolongdatestring?view=netcore-2.2)

When I run:
```
Console.WriteLine($"CurrentCulture is {CultureInfo.CurrentCulture.Name}.");
Console.WriteLine($"DateTimeFormatInfo.CurrentInfo.LongDatePattern: {DateTimeFormatInfo.CurrentInfo.LongDatePattern}");
Console.WriteLine($"DateTime.Now.ToLongDateString(): {DateTime.Now.ToLongDateString()}");
```

the output is:
```
CurrentCulture is en-US.
DateTimeFormatInfo.CurrentInfo.LongDatePattern: MMMM d, yyyy
DateTime.Now.ToLongDateString(): May 15, 2019
```
However, the doc claims the en-US LongDatePattern is: 

> For example, for the en-US culture, the standard long date pattern is "dddd, MMMMdd, yyyy"

**Comment by rpetrusha** [comment]
Thanks for pointing this out, @jwatkin. 

I can only partially reproduce your results. On my Windows 10 systems, the long date pattern is consistently `dddd, MMMM d, yyyy`. What .NET implementation are you running, and what OS are you running it on? Culture-specific formatting information is not constant, but can vary by operating system, .NET implementation, .NET version, and user preferences. 

This particular example is a very stale one that was written for either .NET Framework 1.0 or .NET Framework 1.1 and has not been revised subsequently. We will modify it so that it conforms to current best practices and reflects the output as I've indicated above.

**Comment by jwatkin** [comment]
I'm using Windows 10 Enterprise 1809, under Parallels running on macOS.
The source code is running in a .NET Core 2.2.106 console app:
PM> dotnet --version
2.2.106

**Comment by jwatkin** [comment]
Thank you.
