### ISSUE TITLE
IList Sample C# Code has a Bug

### ISSUE THREAD

**Issue by mvetom** [dotnet/dotnet-api-docs#2951]
Problem:
Look at the C# sample Code for implementing System.Collections.IList at:
https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist?view=netframework-4.8

The RemoveAt method is leaving an extra item at the end of the list

To see this, you can either replace PrintContents() for loop with a foreach loop (after implementing the Enumerator of course)  or simply replace the "i <Count"  in the  PrintContents() for loop with  "i < _contents.Length"

Proposed Solution:   Add  "_contents[Count] = null;"  immediately after the line  "_count--;" in the RemoveAt method.

**Comment by rpetrusha** [comment]
This isn't actually a bug, @mvetom. The array that `SimpleList` wraps is a private fixed array with eight elements. Provided that the _count element is appropriately updated and that the array is iterated only up to the `_count` element and is never enumerated with `foreach`,  it doesn't actually matter whether the last element or elements in the array are removed; they're effectively invisible. The Visual Basic example illustrates this best, since it inadvertently creates an internal array of 9 elements but effectively always hides that last element.

We have opened a PR to correct the Visual Basic code, as well to slightly modernize both the C# and Visual Basic code.

**Comment by mvetom** [comment]
Thanks Rpetrusha,

I understand that the extra element can be hidden, depending on how you iterate through the list. 

However, some users may decided to implement the GetEnumerator and try out foreach -  that's how I ran across this issue.

- Mvetom
