### ISSUE TITLE
Incorrect [Flags] attribute on System.Data.IsolationLevel enum?

### ISSUE THREAD

**Issue by roji** [dotnet/dotnet-api-docs#3141]
[The doc page for System.Data.IsolationLevel](https://docs.microsoft.com/en-us/dotnet/api/system.data.isolationlevel) shows a `[Flags]` attribute that isn't present in the sources, and shouldn't be there. Is that section of the docs auto-generated (and therefore there may be a bug in the process) or should it be fixed manually?

Raised in https://github.com/dotnet/corefx/issues/40848

FWIW [the .NET Framework reference sources](https://referencesource.microsoft.com/#System.Data/fx/src/data/System/Data/IsolationLevel.cs,cbf7cc83d67e54be) don't show the attribute.

/cc @divega @mairaw @carlossanlop

**Comment by rpetrusha** [comment]
Yes, information on the Flags attribute is auto-generated, @roji. Since the attribute isn't applied in either .NET Framework or .NET Core, it's possible that it's present in Xamarin (currently, an attribute is applied if it is present in any of the documented implementation libraries) or that this is a bug. @joelmartinez and @dend, could you take a look?

**Comment by joelmartinez** [comment]
You can see in the EcmaXml metadata that this attribute was present in .NET 1.1:  
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Data/IsolationLevel.xml#L31

```xml
  <Attributes>
    <Attribute FrameworkAlternate="netframework-1.1">
      <AttributeName>System.Flags</AttributeName>
    </Attribute>
  </Attributes>
```

The issue is that we currently don't filter the attributes by the current moniker, which is something that we _will_ be supporting soon as work is in progress/finalizing/testing (SDP pipeline)

**Comment by mairaw** [comment]
This is similar to #2986

I have prioritized this work very high with Mimi for post-SDP.

**Comment by roji** [comment]
Thanks @joelmartinez and @mairaw! I'll close this as a duplicate of #2986.

**Comment by stevendarby** [comment]
#2986 is now closed but It doesn’t appear that this (albeit minor) issue is fixed. If I’m honest, I couldn’t follow everything in the other issue but one of the closing comments was:

>I would recommend to lock this issue in couple of days to prevent accidental piling on discussion here instead of creating new issues where we can have scoped discussions.

Is it worth reopening this issue?
