### ISSUE TITLE
Missing documentation for XElements.Elements method

### ISSUE THREAD

**Issue by Youssef1313** [dotnet/dotnet-api-docs#3260]
The following method is missing:

> public IEnumerable<XElement> Elements(XName name)

Screenshot:

![image](https://user-images.githubusercontent.com/31348972/65875505-b5b2e100-e387-11e9-928b-2d9aeefdbdde.png)

**Comment by mairaw** [comment]
Hi @Youssef1313, thanks for your feedback!

If you look under methods, you'll see that it shows as an inherited API:
https://docs.microsoft.com/en-us/dotnet/api/system.xml.linq.xelement?view=netframework-4.8#methods

![image](https://user-images.githubusercontent.com/12971179/66009992-ea9b6280-e471-11e9-9f48-1c92de24162d.png)

So only APIs defined by the class itself show up in the TOC. This experience is by design.
