### ISSUE TITLE
Large xml files should be split in smaller files

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/dotnet-api-docs#3284]
Take `String.xml` for example. The file is 14333 lines long at the moment I created this issue.

- GitHub [won't let you view the file normally](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml), with xml color coding: the only option is to open it "raw".
- Suggestions in PRs can't be applied: an unexpected error shows up saying that the file has been updated and you need to refresh (which is an incorrect error). I'm encountering that problem in [this PR](https://github.com/dotnet/dotnet-api-docs/pull/3238).
- The user needs to open the file in their local machine, then copy/paste the suggestions manually, one by one.

**Comment by rpetrusha** [comment]
We'll have to see what the impact is on file sizes, @carlossanlop, but the next migration of the API documentation will separate the basic metadata of each type/member and its authored content into separate files. The former will be read-only, and only the authored content will be editable. That should significantly reduce the size of each file and make it far more manageable.

I'm not sure why suggestions can't be applied; I've never encountered it in working with API PRs. I suspect it's a separate issue.

Since planning for the migration is already well under way, I'll close this issue.
