### ISSUE TITLE
.NET Core 3.0 - StringComparison enums no longer supported

### ISSUE THREAD

**Issue by ClairelyClaire** [dotnet/dotnet-api-docs#3287]
Referring to this page:
https://docs.microsoft.com/en-us/dotnet/api/system.stringcomparison?view=netcore-3.0

According to this:
https://github.com/dotnet/corefx/issues/108

InvariantCulture and InvariantCultureIgnoreCase are no longer supported.

**Comment by mairaw** [comment]
Thanks for your feedback @ClairelyClaire. That is a very old issue. It seems that it was brought back in .NET Core 2.0.
@davkean @nguerrera would you know since you commented on that issue?

I see them at the source code: https://source.dot.net/#System.Private.CoreLib/shared/System/StringComparison.cs,eabf4db5f5c52b6a

**Comment by mairaw** [comment]
I agree. Thanks @nguerrera. Also if you filter, you can get the correct fields for each version. So closing the issue.
