### ISSUE TITLE
Define "very short" in Remark for ManualResetEventSlim

### ISSUE THREAD

**Issue by csrakowski** [dotnet/dotnet-api-docs#3323]
The remark for [ManualResetEventSlim](https://docs.microsoft.com/en-us/dotnet/api/system.threading.manualreseteventslim?view=netframework-4.8#remarks) mentions that it provides improved performance[ "when wait times are expected to be very short"](https://github.com/dotnet/dotnet-api-docs/blob/1481150ff6a19d037c9d6271560f9b4e642d62b6/xml/System.Threading/ManualResetEventSlim.xml#L47).

Would it be possible to define "very short", or at least provide some quick high level guidance on whether I should be thinking milliseconds or seconds.

**Comment by mairaw** [comment]
@kouvel any suggestions on what we can add here to the remarks of ManualResetEventSlim?

I think you should be thinking in terms of milliseconds, but let's see what @kouvel says.

**Comment by kouvel** [comment]
The default spin-wait duration for `ManualResetEventSlim` is in the order of ~10 microseconds. If wait times are typically much longer than that, there probably would not be any advantage to spin-waiting. It probably would not help to use a larger spin count in that case either because it would be cheaper to wait. The Slim version also avoids some p/invoke overhead during `Set` and `Reset`, and during `Wait` if the wait completes during the spin-wait.

**Comment by kouvel** [comment]
The default spin-wait duration may differ between runtimes. I think "very short" is appropriate for the doc, as the times may differ between runtimes and maybe between machines.

**Comment by csrakowski** [comment]
Thank you for the answer; microseconds are indeed "very short" (and nowhere close to the +/- 10 seconds interval I need it for), so that answers my use cases.

I am not exactly sure how you would phrase it, but would it possible to add some sort of high level guidance on this to article? 
Something to that tells people to "think in the order of microseconds, not milliseconds".

**Comment by kouvel** [comment]
Yea makes sense, could clarify that
