### ISSUE TITLE
New term for mscorlib/System.Private.CoreLib

### ISSUE THREAD

**Issue by NextTurn** [dotnet/dotnet-api-docs#3387]
The *mscorlib* assembly was renamed to *System.Private.CoreLib* in .NET Core. Do we have a new term for both of them?

![image](https://user-images.githubusercontent.com/45985406/67252365-1e800b80-f4a5-11e9-807c-d5a965cc7f22.png)

**Comment by mairaw** [comment]
@karelz do you have any suggestions?

**Comment by karelz** [comment]
Why would we need a new term for both of them? Where does it show/hurt?

**Comment by NextTurn** [comment]
@karelz I put a screenshot of the search results in the issue description.

**Comment by MSDN-WhiteKnight** [comment]
I don't know a new term, but mscorlib/System.Runtime is sometimes referred to as "core assembly" (for example [CompilerParameters.CoreAssemblyFileName](https://docs.microsoft.com/en-us/dotnet/api/system.codedom.compiler.compilerparameters.coreassemblyfilename)). 

The System.Private.CoreLib is actually a bit special case because it's a runtime-only thing, and it is mentioned almost nowhere in docs. Everything from it shows up in docs as if it resides in System.Runtime, it's design-time counterpart. Usually it's fine, but when using reflection people will encounter System.Private.CoreLib explicitly, which might be confusing. Probably this should be explained somewhere.

**Comment by NextTurn** [comment]
For the specific case of `System.Type.GetType`: calling this method with namespace-qualified type name doesn't work for types implemented in *System.Runtime*, such as `System.IO.FileAttributes`.
