### ISSUE TITLE
The documentation for WebClient.CancelAsync should mention that it is broken and won't be fixed.

### ISSUE THREAD

**Issue by waltdestler** [dotnet/dotnet-api-docs#3777]
The WebClient.CancelAsync method [is broken in .NET Core and will not be fixed](https://github.com/dotnet/corefx/issues/42564). The [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.webclient.cancelasync?view=netframework-4.8) for it should be updated to make this clear so that people don't try to use it.

**Comment by mairaw** [comment]
@karelz @davidsh can you address this feedback?

@gewarren this seems another issue that should go into the breaking changes between Framework and Core.

**Comment by EatonZ** [comment]
I can attest that this needs to be added as a breaking change. I was trying to figure out why this wasn't working going from .NET Framework to.NET Core and I arrived at the [issue @waltdestler created](https://github.com/dotnet/corefx/issues/42564).

Although, I would prefer that this be fixed instead of adding a documentation note telling people that it's broken and to not use it.🙄 `WebClient` is still superior to `HttpClient` in 1 way: it lets you easily track download progress!

**Comment by gewarren** [comment]
This was fixed in https://github.com/dotnet/dotnet-api-docs/pull/4195.
