### ISSUE TITLE
FlagsAttribute mention in CommandBehavior summary misleading 

### ISSUE THREAD

**Issue by Ungerfall** [dotnet/dotnet-api-docs#4334]
The summary says "this enumeration has a <a href="https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute">FlagsAttribute</a> attribute that allows a bitwise combination of its member values", which is rather misleading in a sense that you are allowed to bitwise any enum.
What it actually does is indicates that an enumeration can be treated as a bit field and overrides ToString().

[FlagsAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=netcore-3.1)

**Comment by glihm** [comment]
@Ungerfall hello,

not sure to get the point.

The statement is pretty clear: "__this__ enumeration has a FlagsAttribute...", isn't it?

**Comment by carlossanlop** [comment]
@Ungerfall not sure what is misleading about this.

An enum is not meant to be used as a bitwise enumeration by default. It's when you set the `FlagsAttribute` on top of it, ensure the enum values are powers of two, and ensure the enum has a plural name, that you can use it as a bitwise enumeration.

The example in the page you linked describes how to use the `FlagsAttribute`: https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=netcore-3.1#examples

I'm closing the issue since there is nothing to do.
