### ISSUE TITLE
Docs show VB examples by default (and changing the language doesn't work)

### ISSUE THREAD

**Issue by JansthcirlU** [dotnet/dotnet-api-docs#4398]
**Issue description**

Code examples show VB code by default, regardless of chosen language. Switching to a different language in the language selection menu or selecting a different .NET version does not trigger any changes either.

**Target framework**

Check the .NET target framework(s) being used, and include the version number(s).

- [x] .NET Core
- [x] .NET Framework
- [x] .NET Standard

This bug is version agnostic, at least for this [example](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.indexof).

**Comment by mairaw** [comment]
I've noticed that problem too and I've filed a ticket for the engineering team. Thanks for letting us know @JansthcirlU!

**Comment by Jay-Madden** [comment]
Bump, also seeing this issue

**Comment by JansthcirlU** [comment]
The strangest thing about this bug is that it's not across the entire docs, for example this article on [linked lists](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.linkedlist-1.-ctor?view=netcore-3.1) shows both a C# and a VB example on the same page. And I've also noticed that some articles just work fine (forgot which ones exactly so I can't link them).

**Comment by Youssef1313** [comment]
@mairaw I've checked a few snippets and here are my observations:

1. If the old snippet referencing syntax is used, it always work correctly.
2. If the new syntax is used, it *sometimes* work and sometimes shows the VB only.

However, I haven't checked too many samples to be sure about that.
If the issue will take some time, a temporarily solution would be switching to the old syntax in a single commit and revert it when the issue is fixed.
You may need to try switching to the old-syntax and check if it works in the staging site.

**Comment by mairaw** [comment]
This issue was fixed today. It was indeed related to the new syntax for code snippets.

Rolling back to the old syntax would be a bit painful since the old syntax doesn't support all the interactive scenarios that the new syntax does.

Apologies for the inconvenience.
