### ISSUE TITLE
Span<T> referred to as class instead of struct

### ISSUE THREAD

**Issue by kiapanahi** [dotnet/dotnet-api-docs#5041]
In the `Span<T>` [document for netcore-3.1](https://docs.microsoft.com/en-us/dotnet/api/system.span-1?view=netcore-3.1) under the _Remarks &gt; Span&lt;T&gt; and memory_ section, it is pointed that:

> Because Span&lt;T&gt; is an abstraction over an arbitrary block of memory, methods of the Span&lt;T&gt; **_class_** and methods with Span&lt;T&gt; parameters operate on any Span&lt;T&gt; object regardless of the kind of memory it encapsulates.

Is this a simple mistake or is written purposefully?

**Comment by gouravmpk** [comment]
n the context of Span<T>, the term "abstraction over an arbitrary block of memory" means that you can use Span<T> to work with memory in a way that's independent of the specific type of memory it encapsulates. This allows you to write code that operates on memory regions without being concerned about whether the memory is on the stack, on the heap, part of an array, or some other source.

The key benefit of this is that it provides performance improvements and safety guarantees by avoiding unnecessary memory copies and enabling optimizations. So, you can confidently use methods of the Span<T> class and methods with Span<T> parameters on any Span<T> object, regardless of the underlying memory source.

This design is intentional and aligns with the goals of providing efficient and safe memory manipulation in C# and .NET. It's not a mistake in the documentation but rather a fundamental characteristic of how Span<T> is designed to work.

**Comment by kiapanahi** [comment]
Thank you for the comment.

The issue was with the usage of the phrase "***class***" (16<sup>th</sup> word in the quoted text) as mentioned in the original issue's quoted text. the type `Span<T>` is actually a `readonly ref struct` and not a `class`.

The issue is apparently fixed now that I rechecked the documentation.
