### ISSUE TITLE
Path.GetInvalidPathChars specifies the wrong characters

### ISSUE THREAD

**Issue by Forgind** [dotnet/dotnet-api-docs#5292]
I'm not sure if this is better as a docs bug or a product bug, but I imagine it would be a breaking change for a lot of people at this point.

The docs [here](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/Path.xml) specify that "on Windows-based desktop platforms, invalid path characters might include ASCII/Unicode characters 1 through 31, as well as quote ("), less than (<), greater than (>), pipe (|), backspace (\b), null (\0) and tab (\t)." Someone external wrote a test relying on this, and it failed. testing it on my windows-based desktop platform, the characters it returned did not include all of these either. Note that I still couldn't make a folder with them, so the docs matches the file system, just not this method.

**Comment by carlossanlop** [comment]
I see what the problem is. Whoever documented this API's remarks, copied them directly from `Path.GetInvalidFileNameChars`, which _does_ return the set of characters you described.

The remarks for `GetInvalidPathChars` needs to be updated to list the correct list of characters.

`Path.GetInvalidFileNameChars()`
[dotnet/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L19-L26](https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L19-L26)

```cs
 public static char[] GetInvalidFileNameChars() => new char[]
{
    '\"', '<', '>', '|', '\0',
    (char)1, (char)2, (char)3, (char)4, (char)5, (char)6, (char)7, (char)8, (char)9, (char)10,
    (char)11, (char)12, (char)13, (char)14, (char)15, (char)16, (char)17, (char)18, (char)19, (char)20,
    (char)21, (char)22, (char)23, (char)24, (char)25, (char)26, (char)27, (char)28, (char)29, (char)30,
    (char)31, ':', '*', '?', '\\', '/'
};
```

`Path.GetInvalidPathChars()`
[dotnet/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L28-L35](https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Private.CoreLib/src/System/IO/Path.Windows.cs#L28-L35)
```cs
public static char[] GetInvalidPathChars() => new char[]
{
    '|', '\0',
    (char)1, (char)2, (char)3, (char)4, (char)5, (char)6, (char)7, (char)8, (char)9, (char)10,
    (char)11, (char)12, (char)13, (char)14, (char)15, (char)16, (char)17, (char)18, (char)19, (char)20,
    (char)21, (char)22, (char)23, (char)24, (char)25, (char)26, (char)27, (char)28, (char)29, (char)30,
    (char)31
};
```

`Path.InvalidPathChars`
[dotnet/runtime/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs#L35](https://github.com/dotnet/runtime/blob/79ae74f5ca5c8a6fe3a48935e85bd7374959c570/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs#L35)
```cs
[Obsolete("Please use GetInvalidPathChars or GetInvalidFileNameChars instead.")]
public static readonly char[] InvalidPathChars = GetInvalidPathChars();
```
