### ISSUE TITLE
Better explanation of GCMemoryInfo properties

### ISSUE THREAD

**Issue by loop-evgeny** [dotnet/dotnet-api-docs#6756]
The new GCMemoryInfo added in .NET 5.0 seem very promising, but many of them are not well documented on https://docs.microsoft.com/en-us/dotnet/api/system.gcmemoryinfo?view=net-5.0

For example:

- **MemoryLoadBytes**: `Gets the memory load when the last garbage collection occurred.` That's great, but what *is* the memory load? That's not a common, well-understood term, to my knowledge, and a web search for ".NET memory load" does not explain it.
- **PauseDurations** : `Gets the pause durations. For blocking GCs, there is one pause; for background GC, there are two.` OK, that's something, but why are there 2 for BGCs? What do I do with the 2 TimeSpans? Just add them together? Or do they mean something different? Is this the pause duration only for the one GC at the returned `Index` or all GCs up to and including that one? If it's for all GCs, and I pass in a GCKind is it then the total pause duration for all GCs of that kind? But what about GCKind.Any? (`PauseTimePercentage` is explained well, but I'm not sure if I can assume the same applies to `PauseDurations`.)
- **PromotedBytes**: `Gets the promoted bytes for this GC.` - promoted from which generation to which? When I request GCKind.FullBlocking I get non-zero values, so I guess it must be *to* gen 2? Or does it include bytes promoted from gen 0 to gen 1 as well?
- **TotalCommittedBytes**: `Gets the total committed bytes of the managed heap.` It would be useful to include here what OS metrics this should correspond to on Windows, Linux and macOS, i.e. if I was trying to find the same info from the OS, how would I do that?
- **HighMemoryLoadThresholdBytes**: `Gets the high memory load threshold when the last garbage collection occurred.` What is the "high memory load threshold" - what is the significance of this?
- **Compacted** and **Concurrent**: links to explanations of what these are would be useful, though these are easily findable

**Comment by GrabYourPitchforks** [comment]
@Maoni0 I assigned to you for now because I believe you're best qualified to answer this.

**Comment by loop-evgeny** [comment]
17 months on the documentation does not seem to have changed. I'm probably not the only one who doesn't use this API because they don't understand it.

**Comment by Maoni0** [comment]
memory load is a common concept on Windows. it's a field in `MEMORYSTATUS` obtained by the [GlobalMemoryStatus](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-globalmemorystatus) API -

> dwMemoryLoad

> A number between 0 and 100 that specifies the approximate percentage of physical memory that is in use (0 indicates no memory use and 100 indicates full memory use).

the 2 pauses for BGC are explained in our docs: https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/background-gc.

PromotedBytes says "Gets the promoted bytes for this GC" - this GC is collecting some generations, it's whatever that survived from those generations. 

TotalCommittedBytes - this is the amount of backing store for the memory. on windows this is exactly what it is, the committed bytes, ie, we call VirtualAlloc with MEM_COMMIT. on linux this is when we change the page mapping to PROT_WRITE | PROT_READ. 

HighMemoryLoadThresholdBytes - this is explained [here](https://github.com/Maoni0/mem-doc/blob/master/doc/.NETMemoryPerformanceAnalysis.md#gc-is-per-process-but-is-aware-of-physical-memory-load-on-the-machine). excerpt - 

> GC is per process but is aware of physical memory load on the machine
GC is a per process component (and always has been since the inception of the CLR). Most of the GC perf heuristics are based on per process measurements but GC is aware of the global physical memory load on the machine. We do this because we want to avoid getting into a paging situation. GC recognizes a certain memory load percentage as "high memory load situation". When the memory load percentage is over that, GC goes into a more aggressive mode, i.e., it would choose to do more full blocking GCs if it thinks they are productive because it wants to reduce the heap size.

> Currently on smaller machines (ie, < 80 GiB memory), by default GC treats 90% as high memory load. On machines with more memory, this is between 90% and 97%. This threshold can be adjusted by the [COMPlus_GCHighMemPercent](https://docs.microsoft.com/en-us/dotnet/core/run-time-config/garbage-collector#high-memory-percent) environment variable (or System.GC.HighMemoryPercent config in runtimeconfig.json starting .NET 5). The main reason why you would want to adjust this is to control heap size. For example, on a machine with 64 GB memory, for the main dominant process it’s reasonable for GC to start reacting when there’s 10% memory available. But for smaller processes (for example, if a process only consumes 1 GB memory), GC can comfortably run with < 10% memory available so you might want to set it higher for those processes. On the other hand, if you want the larger processes to have smaller heap sizes (even when there’s a plenty of available physical memory on the machine), adjusting this lower would be an effective way for GC to react sooner to compact the heap down.

GH notification is not that reliable. I didn't see this till now.

**Comment by loop-evgeny** [comment]
Thanks a lot for the explanations! Those would definitely be helpful to have in the official docs.

**Comment by Maoni0** [comment]
hi @gewarren, do you think you could help adapt what I mentioned above into the official doc for this API? in the past I've been told that API docs just come from code comments marked with "///". but if we could have more detail that's helpful to customers (and is too much to put in code comments) it'd be good to do that...
