### ISSUE TITLE
Remove all Quic docs

### ISSUE THREAD

**Issue by danmoseley** [dotnet/dotnet-api-docs#6957]
System.Net.Quic will not ship as public API in .NET 6.0. We need to remove all the docs for it: https://docs.microsoft.com/en-us/dotnet/api/system.net.quic?view=net-6.0 and below.

cc @ManickaP @karelz

**Comment by danmoseley** [comment]
@gewarren  these API no longer appear in the reference assembly but are still public in the code (for ASP.NET). Given that, if we simply delete the topics here will they reappear later?

**Comment by gewarren** [comment]
If they've been removed from the reference assembly then I *think* they will be deleted the next time we update the .NET 6 APIs (since each preview version overwrites the last published version instead of creating a new moniker). But if you don't want to wait for that, you could probably just delete them. They'll also need to be removed from xml/FrameworksIndex/net-6.0.xml. Is https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.quicimplementationprovider?view=net-6.0#System_Net_Http_SocketsHttpHandler_QuicImplementationProvider removed too?

**Comment by ManickaP** [comment]
`QuicImplementationProvider` is removed as well. Should I rather do the removal manually now or are we ok with waiting and letting automation handle it?

**Comment by carlossanlop** [comment]
@ManickaP xml files should not be deleted manually from dotnet-api-docs.

The referenced Prev7 PR should automatically address this issue.
