### ISSUE TITLE
HttpClient needs proper guidance

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/dotnet-api-docs#7285]
HttpClient needs official guidance on how to use it properly. Currently MS docs mention only two ways of how we should use it:
* (a) singleton static instance (for console apps)
* (b) HttpClientFactory via DI in ASP.NET apps.

But that's not enough.

For example, here's one MS doc at https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0 that literally says 

> HttpClient is intended to be instantiated once and re-used throughout the life of an application

But it never mentions that in that case, **HttpClient will ignore DNS changes**. This issue has been reported multiple times on github and stackoverflow. And to fix the DNS problem we need to use a special constructor:

```
new HttpClient(new SocketsHttpHandler
{
	PooledConnectionLifetime = TimeSpan.FromMinutes(20) //recreate every 20 minutes
});
```

But MS docs never mention this fix. I found it accidentally, after hours of searching github for comments from MS employees.

The only more or less full (ish) guidance I found is in this comment: https://github.com/dotnet/aspnetcore/issues/28385#issuecomment-853766480 but its not even written by MS, just some good Samaritan who decided to help everyone.

Please read the comment and reflect the docs

**Comment by geoffkizer** [comment]
> HttpClient will ignore DNS changes

Just to be clear, the problem is not that HttpClient (or rather, SocketsHttpHandler) ignores DNS changes generally. SocketsHttpHandler correctly handles DNS changes when creating new connections.

The problem is that once a connection is established, SocketsHttpHandler assumes it can continue to use this connection until the server closes it. Or to state that the other way around: SocketsHttpHandler assumes that if the connection shouldn't be used anymore, the server will close it. This works fine for many scenarios.

The problem occurs when you switch your DNS mappings and remove an existing IP entry (or entries), but the server at that IP address continues to handle requests on the previously-established connections. In that case, SocketsHttpHandler will just keep using those previously-established connections, unaware that they are no longer valid according to the latest DNS values.

`PooledConnectionLifetime` was introduced to solve this problem. It does so by simply discarding connections once they hit a certain age. Eventually the old connections will be discarded and new ones will be created, and the new connections will respect the new DNS values when they are created.

This isn't ideal for a couple reasons:
(1) Connections get discarded regardless of whether they are still valid per current DNS or not.
(2) This introduces a trade-off between performance and correctness. If you want SocketsHttpHandler to respond quickly to DNS changes, then you need to set this to a relatively small value. But the smaller you set it, the more often you'll need to create new connections, which will impact performance.

On top of that, we clearly don't do a good job of explaining this.

I wonder if we could handle this better in SocketsHttpHandler. One idea is to add a new setting like `PooledConnectionDNSRevalidationPeriod`. This would be similar to `PooledConnectionLifetime`, except that when the specified time period expires, we would "revalidate" the connection by checking whether the IP address used to establish it is still valid in DNS or not. If it is, we can keep using it. If not, just discard it, like we do with `PooledConnectionLifetime` today.

The nice thing about this approach is that, assuming the revalidation logic is relatively cheap, we could enable this by default with a relatively low time period, such that it would hopefully just work for most users. If you don't care about DNS changes, then there's a small added cost to the revalidation, but hopefully it's so small you wouldn't notice (and you can always disable it completely if you want). If you do care about DNS changes, then the default behavior hopefully works reasonably well for you, and you can tune it further if necessary.

**Comment by antonfirsov** [comment]
Opened #60390 so we can track this idea. Independently from that, we should still do better job documenting the current behavior.
