### ISSUE TITLE
MethodInfo.Invoke

### ISSUE THREAD

**Issue by NetMage** [dotnet/dotnet-api-docs#820]
MethodInfo.Invoke link under Methods in Tree goes to .Net 1.1 page instead of MethodBase.Invoke page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc2c5677-4ada-334c-6fe1-13329ed66839
* Version Independent ID: 33eda1ff-e736-e2f4-a44b-14f3da3d7a7b
* Content: [MethodInfo Class (System.Reflection)](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo?view=netframework-4.7.1)
* Content Source: [xml/System.Reflection/MethodInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Reflection/MethodInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @rpetrusha
* Microsoft Alias: **ronpet**

**Comment by rpetrusha** [comment]
Since this is a build issue related to versioning, I'll close this issue. The corresponding issue is MicrosoftDocs/issues#579. Currently, it's closed, but I've asked that it be reopened.

**Comment by mairaw** [comment]
@joelmartinez when I look at the internal backup of the msdn docs, I don't see this member as part of the MethodInfo class and it shows as inherited from MethodBase instead. Is that a bug on MSDN or on our current tooling?

**Comment by mairaw** [comment]
Reopening since docs are missing for this API but I want to check whether we need to document it or not. The experience on docs is already tracked separately.

**Comment by joelmartinez** [comment]
@mairaw I haven't looked at the metadata for this particular type to verify, but I'm going to guess that this is what's going on … it's probably due to this behavior in mdoc:

1. When there is a virtual member (say `SomeBaseClass.AVirtualMember`), it is obviously documented in `SomeBaseClass.xml`.
2. If a class (let's call it `AnotherClass`) inherits from `SomeBaseClass`, and **override**s `AVirtualMember`, it is *also* documented in `AnotherClass.xml`.

The reasoning here is that if a class is overriding a base class' member, then it stands to reason that the behavior might differ in that class' implementation … so this gives authors a chance to document that unique behavior in the class that it exists.
