### ISSUE TITLE
List<T>.AddRange should document the behavior in the case of enumerator exceptions

### ISSUE THREAD

**Issue by ajtribick** [dotnet/dotnet-api-docs#9412]
The documentation for `List<T>.AddRange(IEnumerable<T>)` should state what happens in case iterating the `IEnumerable<T>` throws an exception. From experimentation this seems to be that the `List<T>` is left containing all the elements that have been successfully yielded (which seems pretty reasonable to me), but at the moment it is not clear whether or not this is a guarantee of the method's contract or something that could potentially be changed in future .Net updates.

**Comment by krwq** [comment]
IMO this doesn't differ from any other API expecting interface/abstract which randomly throws. You should design your enumerable implementations such that it doesn't throw during enumeration - if it's supposed to throw because of arguments it should do very early before it yields any results. Otherwise you likely shouldn't be using lazy enumeration in the first place (i.e. your implementation can produce collection). I don't believe documenting every case of wrong implementation makes sense.

Another example is class which has a property with throwing getter and trying to serialize it into a stream - IMO it doesn't make sense to document what will happen with the stream (i.e. how much data will be written) - it's clearly class implementation problem

**Comment by ajtribick** [comment]
@krwq - the problem is that the framework already supplies various cases of `IEnumerable<T>` which can throw during iteration for reasons beyond the programmer's control, an example being the result of `File.ReadLines()`, where the iterator implementation does nothing to stop the propagation of exceptions (e.g. `IOException`) thrown by the stream/text reader. If that is an inappropriate use of `IEnumerable<T>`, then the documentation of `File.ReadLines()` should state that its result does not meet the requirements of the `IEnumerable<string>` contract with regards to exceptions and should not be used with framework-supplied methods like `List<string>.AddRange()`.

In any case, as one of the basic collection types supplied by the framework, it is important to document the behavior in the exception case to allow the implementors of higher-level classes to be able to make decisions on how to provide their own exception guarantees (e.g. by re-implementing methods that provide insufficiently strong guarantees).

**Comment by krwq** [comment]
For that specific case why aren't you using File.ReadAllLines? What behavior would you expect? I don't think there will be anything we can propose which everyone will be happy with. I'd personally design my apps such that I'm not depending on these kind of nuances. I.e. you can write your own wrapping IEnumerable which will i.e. skip all entries which caused errors or stop enumerating so that you have predictable behavior - your implementation can choke all exceptions and store them somewhere if needed.
Note that in most of the cases File.ReadLines will not throw and errors suggest something really bad.

One thing you can do is to use List constructor taking IEnumerable rather than Add method - this way you won't have semi filled object in the first place.

IMO documenting what will happen if the implementation of the interface does something unexpected is not really helpful but will take a lot of time to do.

**Comment by ajtribick** [comment]
```
For that specific case why aren't you using File.ReadAllLines? 
```

Because that might not be all I'm doing there. I might be combining lines from multiple files into the same list, calling `AddRange` once per file. I might be using LINQ on the result of `File.ReadLines` to filter out all lines starting with `#`, etc. etc.

As a concrete example

```csharp
var nonCommentLines = new List<string>();
foreach (var filename in GetSomeFilenames())
{
    try
    {
        nonCommentLines.AddRange(File.ReadLines(filename).Where(line => !line.StartsWith('#')));
    }
    catch (IOException e)
    {
        // are the lines read from the previous files guaranteed to still be there?
        // do I need to clear out the lines read from the current file?
    }
}
```

With the current state of the documentation, the answers to the questions in the `catch` block appear to be "no" and "unknown" - all that we can say is `nonCommentLines` is a valid list in some otherwise completely unspecified state. The only possible recovery would then be to start from scratch with an empty list.

Now while I would say that documenting what would happen if the passed in object does not meet the contract of the interface at all would be a waste of time, it appears by virtue of the fact that .Net does provide fallible IO-backed `IEnumerator<T>` implementations, that `MoveNext()` throwing is a valid behavior.

But as you seem to strongly disagree, I would suggest as an alternative to focus on documenting that `File.ReadLines()` returns an incorrect iterator implementation that does unexpected things as regards its interaction with other .Net iterator methods.
