### ISSUE TITLE
Offset clarification

### ISSUE THREAD

**Issue by IMarvinTPA** [dotnet/dotnet-api-docs#947]
Please clarify if the offset parameter is from the beginning of the file or if it is from the current position.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f3448af-b733-a7a8-8ef1-a3b5f88a791f
* Version Independent ID: 436e4fb5-5f78-ae3f-a99c-489c2ea9f703
* Content: [FileStream.Read(Byte\[\], Int32, Int32) Method (System.IO)](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.read?view=netframework-4.7.2)
* Content Source: [xml/System.IO/FileStream.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.IO/FileStream.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by mairaw** [comment]
@Thraka can you please update the milestone accordingly?

**Comment by Thraka** [comment]
Looking at this further I don't think there is a way to make it clearer. The suggestion being made (once the problem was figured out) was that the parameter name could be more descriptive, but we're probably not going to change that via docs 😄 

The description for the parameter seems accurate and descriptive.
