### ISSUE TITLE
Sample not working 

### ISSUE THREAD

**Issue by PeterSchwalm** [dotnet/dotnet-api-docs#949]
the example for asynchronous does not look like working. I need an example for displaying the output (stderror and stdout) of the spawned process, while the process is running.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3991f67b-8387-5ae5-2f0a-782466233ed6
* Version Independent ID: 843917c4-f01e-5baa-454c-52a8d011bd89
* Content: [ProcessStartInfo.RedirectStandardOutput Property (System.Diagnostics)](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput?view=netframework-4.7.2)
* Content Source: [xml/System.Diagnostics/ProcessStartInfo.xml](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Diagnostics/ProcessStartInfo.xml)
* Product: **dotnet-api**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by rpetrusha** [comment]
I suspect the problem here is that the example description, which says that the standard output stream is read asynchronously, doesn't correspond to the example code, which reads the standard error stream asynchronously. dotnet/dotnet-api-docs#2048 and dotnet/samples#725 address this issue, provide a simple example that Process.Start can launch, and add complete examples rather than code fragments.

Thanks for bringing this issue to our attention, @PeterSchwalm.
