### ISSUE TITLE
ContextMenu

### ISSUE THREAD

**Issue by ThrowsGithub** [dotnet/dotnet-api-docs#9733]
System.Windows.Forms.ContextMenu 这个对象，在.net 8中不存在，只有在.netframwork中存在。

**Comment by lextm** [comment]
1. This repo in general only accepts issues in English so that others can review them.
2. [The current documentation has nothing wrong](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.contextmenu). Like "Applies to" section indicates, this type is available on all .NET Framework versions, but only available in .NET Core 3.0 (as it was first removed in .NET Core 3.1).
