### ISSUE TITLE
Add information about cookie storage details

### ISSUE THREAD

**Issue by o-alexandre-felipe** [dotnet/dotnet-api-docs#9849]
```c-sharp
using System.Net.WebSockets;
using System.Net.Http;
```

What is the default `ClientWebsocket.Options.Cookies`?

At which level is the default storage shared? 
- per instance?
- per application?
- per domain?
- global?

What is the persistence?
- until connection is destructed?
- until applicaiton is closed?
- until OS is shutdown?
- other?

Also, how are cookies handled when using `HttpClient`? It is stated that cookie storage can be controlled by [HttpClientHandler.UseCookies](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.usecookies?view=net-8.0), again is not clear (to me, at the moment) what is the scope of those cookies?

**Comment by ManickaP** [comment]
@CarnaViire

**Comment by ManickaP** [comment]
For `HttpClient`, it's per the instance of the client.

**Comment by CarnaViire** [comment]
> What is the default ClientWebsocket.Options.Cookies?

`null`

> At which level is the default storage shared?

The _default_ storage is not shared, because there's no storage by default. If you do specify `ClientWebSocket.Options.Cookies`, then they would be used only for this specific WebSocket handshake request. Technically, you can say it's "per instance".

However, there's an option to pass in a custom `HttpClient` (`HttpMessageInvoker`) to the [`ClientWebSocket.ConnectAsync(Uri, HttpMessageInvoker, CancellationToken)`](https://learn.microsoft.com/en-us/dotnet/api/system.net.websockets.clientwebsocket.connectasync?view=net-8.0#system-net-websockets-clientwebsocket-connectasync(system-uri-system-net-http-httpmessageinvoker-system-threading-cancellationtoken)) overload. This overload is _not_ compatible with any `HttpClient`-related properties in `ClientWebsocket.Options`, as it is expected for the user to set them up directly on the to-be-passed `HttpClient` (and/or on the `HttpMessageHandler` instance used to create `HttpClient`).

This would include a `CookieContainer`, that, as @ManickaP mentioned, is per `HttpClient` (to be more precise, per [`HttpClientHandler`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclienthandler.cookiecontainer?view=net-8.0) or [`SocketsHttpHandler`](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.cookiecontainer?view=net-8.0)) instance, so if you reuse the `HttpClient` for multiple `ClientWebSocket`s, you will end up reusing the `CookieContainer` as well.

**Comment by ManickaP** [comment]
Hope your question got answered. I'll close this.
