### ISSUE TITLE
.NET FileSecurity documentation error

### ISSUE THREAD

**Issue by emmarker** [dotnet/dotnet-api-docs#9865]
The [.NET 8 FileSecurity documentation](https://learn.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.filesecurity?view=net-8.0) has incorrect [examples](https://learn.microsoft.com/en-us/dotnet/api/system.security.accesscontrol.filesecurity?view=net-8.0#examples)

This document recommends the use of [SetAccessControl](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileinfo.setaccesscontrol?view=netframework-4.8.1) and [GetAccessControl](https://learn.microsoft.com/en-us/dotnet/api/system.io.fileinfo.getaccesscontrol?view=netframework-4.8.1) through the File class, which does not work in .NET 8
<img width="183" alt="image" src="https://github.com/dotnet/dotnet-api-docs/assets/130802201/ea499a96-219d-458c-8fb6-68344b642739">

The example should be modified to use `new FileInfo(fileName).SetAccessControl(fSecurity)`

The reference links in the .NET 8 documentation also redirect to .NET Framework documentation, which is confusing for users.

<img width="656" alt="image" src="https://github.com/dotnet/dotnet-api-docs/assets/130802201/a0759c32-2329-4eee-aeef-a6a4c35e4a98">

<break/><break/>

<img width="674" alt="image" src="https://github.com/dotnet/dotnet-api-docs/assets/130802201/03d7a62c-5186-4c40-9005-297fd1b5b28c">

---
[Associated WorkItem - 261123](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261123)

**Comment by adamsitnik** [comment]
> The example should be modified to use `new FileInfo(fileName).SetAccessControl(fSecurity)`

I agree. Would you like to send a PR with a fix?

> The reference links in the .NET 8 documentation also redirect to .NET Framework documentation, which is confusing for users.

My guess it's because `File.SetAccessControl` and `FileInfo.SetAccessControl` don't exist in .NET (Core), but we provide extension methods for `FileInfo`:

![image](https://github.com/dotnet/dotnet-api-docs/assets/6011991/1ba31329-e922-4068-bc53-676fbeb98fa7)

![image](https://github.com/dotnet/dotnet-api-docs/assets/6011991/86ecb1d2-f914-4575-8e5a-2188493d936a)

@gewarren is it possible to customize the redirection for this API?

**Comment by gewarren** [comment]
@adamsitnik I can fix this - thanks.
