### ISSUE TITLE
Add to the docs what the units of measure for Length and CompressedLength properties on ZipArchiveEntry are

### ISSUE THREAD

**Issue by kaypee90** [dotnet/dotnet-api-docs#9882]
https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.ziparchiveentry.compressedlength?view=netcore-3.1

**Comment by carlossanlop** [comment]
Thanks for reporting. It's bytes. That is almost always the default unit of measurement of data, unless otherwise specified.

But we could welcome a fix if that would help clarify the description. Would you like to contribute and provide that fix in a PR, @kaypee90?

You would modify these lines:

- https://github.com/dotnet/dotnet-api-docs/blob/2b6497e5a2f5cd62572107fd5eacb35e6ac8a352/xml/System.IO.Compression/ZipArchiveEntry.xml#L160

- https://github.com/dotnet/dotnet-api-docs/blob/2b6497e5a2f5cd62572107fd5eacb35e6ac8a352/xml/System.IO.Compression/ZipArchiveEntry.xml#L438

**Comment by kaypee90** [comment]
@carlossanlop I have opened a PR for this issue
