### ISSUE TITLE
JsonNode.GetValueKind does not work on .NET 6 and 7, but page says it does.

### ISSUE THREAD

**Issue by vebcaster** [dotnet/dotnet-api-docs#9919]
This page https://learn.microsoft.com/en-us/dotnet/api/system.text.json.nodes.jsonnode.getvaluekind?view=net-8.0 says that JsonNode.GetValueKind applies to .NET 6, 7, 8, 9. But it does not work on 6 & 7. Only on 8 (and probably 9).

**Comment by gewarren** [comment]
@vebcaster - When you say it doesn't work, what do you mean exactly? That the API isn't available?

**Comment by colejohnson66** [comment]
On .NET 7 and earlier, you must reference the [System.Text.Json](https://www.nuget.org/packages/System.Text.Json) NuGet package.

https://apisof.net/catalog/b375c8021f1d0888ff72d7c28638e3a2

**Comment by gewarren** [comment]
The page does show which package is needed for .NET 7:

<img width="682" alt="image" src="https://github.com/dotnet/dotnet-api-docs/assets/24882762/c8e19ad8-3537-44d5-b608-9f1fc00eed80">

I realize that the docs also show a package for .NET 8/9, because that version of the API essentially hides the "in-box" version. We're working on a fix for that, and I've added a link to this issue in that internal work item.
